# Generated by Django 5.0.4 on 2024-05-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_urls_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='user_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
