# Generated by Django 5.0.4 on 2024-05-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_urls_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='urls',
            name='slug',
            field=models.CharField(max_length=6),
        ),
    ]
