# Generated by Django 5.0.4 on 2024-05-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_urls_name_alter_urls_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='slug',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
