# Generated by Django 5.0.4 on 2024-05-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_urls_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='clientIP',
            field=models.CharField(default='xxx.xxx.xxx.xxx', max_length=20),
            preserve_default=False,
        ),
    ]
