# Generated by Django 5.0.4 on 2024-05-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_visits_clientip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visits',
            name='clientIP',
        ),
    ]
